### PR TITLE
BindFS - Serria 10.12 - User/Group remap on nfs shares

### PR DESCRIPTION
**Pull request by gilleyj**

### CODE REVIEW

**Comment by till** [comment]
@gilleyj can we merge this?

**Comment by gilleyj** [comment]
@till, I imagine so, it actually worked for me for my NFS mounts and the serria user/group issue.

I do not know the ramifications of how this would work on Linux which is why I left this open.

**Comment by till** [comment]
@gilleyj do we use bind-fs somewhere?

**Comment by gilleyj** [comment]
@till, no, just looked through the varous vagrants and I believe I am the only one who had installed bindfs to solve this issue.  Lets close this without merge.

**Pull request closed without merging**
